UPDATE scene_synopses SET synopsis = 'Richard of York pursues Clifford across the battlefield of Towton, burning for revenge against the man who killed both his father York and his young brother Rutland in cold blood. Clifford, exhausted and wounded, flees into the thick of the fighting. Richard calls out challenges but cannot reach him through the press of soldiers. Clifford disappears into the battle without Richard able to deliver the vengeance he seeks. The scene is brief and urgent, capturing the chaos and personal hatred that drives the Wars of the Roses beyond politics into blood feud.' WHERE work_abbrev = '3H6' AND div1 = 2 AND div2 = 4;

UPDATE scene_synopses SET synopsis = 'The Countess of Rossillion gives her clown Lavatch a letter to carry to Helena in Paris, where Helena is at court attempting to cure the dying King of France. Lavatch is earthy and irreverent, and the scene provides a comic break as he describes what he imagines court life to be like in vivid, absurd terms. The Countess good-naturedly tolerates his jesting while making sure her message will reach Helena. The scene shows the Countess''s warmth and her quiet support for Helena''s bold plan. It also keeps the audience aware that events in Paris are unfolding even while we pause in Rossillion.' WHERE work_abbrev = 'AWW' AND div1 = 2 AND div2 = 2;

UPDATE scene_synopses SET synopsis = 'Bertram makes his final preparations to leave Paris for the wars in Florence, eager to escape the marriage the King forced him into with Helena. When Helena approaches him tenderly and asks for a farewell kiss, Bertram coldly refuses, treating her with contempt rather than as his wife. He hands her letters and orders her to return to his mother in Rossillion, dismissing her with barely concealed disdain. Without warmth or hesitation he departs immediately for Italy, leaving Helena humiliated and alone. The scene crystallizes how completely Bertram rejects Helena and sets in motion the desperate plan she will devise to win him.' WHERE work_abbrev = 'AWW' AND div1 = 2 AND div2 = 5;

UPDATE scene_synopses SET synopsis = 'In Florence, the Duke of Florence formally presents Bertram with command of his cavalry, recognizing the young Englishman''s eagerness for military glory. Bertram accepts the honor with pride, having found on the battlefield the freedom and status he could not find at home in Rossillion. He throws himself into soldiering as an escape from the marriage he despises and the life he fled. The scene is short but important, showing Bertram flourishing in war while Helena works her quiet plan back in France. His valor in Florence will later be cited as evidence that he is worth redeeming despite his callous behavior.' WHERE work_abbrev = 'AWW' AND div1 = 3 AND div2 = 3;

UPDATE scene_synopses SET synopsis = 'Helena and her companion the Widow arrive in Marseilles after a long journey, only to discover that the King of France has already left and traveled on to Rossillion. Having come all this way to present proof of her fulfilled mission to the King, Helena must now press on further without rest. She thanks the Widow for her continued loyalty and they immediately set out again for Rossillion. The scene underscores Helena''s determined persistence: no obstacle, no delay, no weariness can stop her from completing what she has set out to do. The bed-trick has been accomplished, and the final confrontation with Bertram now approaches.' WHERE work_abbrev = 'AWW' AND div1 = 5 AND div2 = 1;

UPDATE scene_synopses SET synopsis = 'Orlando and his elderly servant Adam stagger into the Forest of Arden, both exhausted from their long flight from Oliver''s estate. Adam is completely spent and sinks down, telling Orlando he can go no further and fears he will die here in the forest. Orlando refuses to leave him and promises to find food and shelter before allowing Adam to perish. He gently settles Adam and goes off alone into the forest to search for provisions. The scene is quietly moving: Adam sacrificed his life savings for Orlando''s escape, and Orlando''s tender care of him shows the same loyalty returned. It sets up Orlando''s encounter with Duke Senior''s company.' WHERE work_abbrev = 'AYL' AND div1 = 2 AND div2 = 6;

UPDATE scene_synopses SET synopsis = 'The melancholy Jacques joins a group of Duke Senior''s lords who have just killed a deer in the Forest of Arden. The lords sing a hearty celebratory song, crowning the successful hunter with the deer''s antlers as a trophy and badge of honor. The mood is boisterous and comic, offering a burst of song and good spirits in the middle of the forest scenes. The deer''s antlers carry a secondary jest — horns traditionally symbolized a cuckold — but the lords embrace the image with cheerful irreverence. The brief scene keeps the forest world feeling alive and festive even amid the play''s more serious romantic entanglements.' WHERE work_abbrev = 'AYL' AND div1 = 4 AND div2 = 2;

UPDATE scene_synopses SET synopsis = 'Touchstone, the court fool now living in the forest, and Audrey, the simple country girl he intends to marry, look forward eagerly to their wedding planned for the following day. Two pages from Duke Senior''s company arrive and, at Touchstone''s request, sing them a bright, cheerful spring song celebrating love and the season. Touchstone critiques the performance with his usual ironic detachment, though it''s plain he is content. The scene is light and warm, signaling that the play is moving toward its multiple weddings and happy resolution. Even the oddest match in the play — the sophisticated fool and the guileless goatherd — is finding its joyful conclusion.' WHERE work_abbrev = 'AYL' AND div1 = 5 AND div2 = 3;

UPDATE scene_synopses SET synopsis = 'At the family monument, Claudio and Don Pedro arrive in the dead of night to perform a solemn act of penance for Hero, whom Claudio believes he shamed to death with his false public accusation at the altar. Claudio reads aloud a formal epitaph he has written for Hero, honoring her name and confessing the wrong done to her. Don Pedro joins him in pledging that they will return each year to mourn and remember her. Having fulfilled this duty, they depart to prepare for the wedding Leonato has arranged, where Claudio has agreed to marry Leonato''s unknown niece as restitution. The scene marks Claudio''s genuine remorse before the joyful revelation that Hero is alive.' WHERE work_abbrev = 'Ado' AND div1 = 5 AND div2 = 3;

UPDATE scene_synopses SET synopsis = 'Hubert meets the Bastard Faulconbridge in the dark and delivers devastating news: King John has been poisoned by a treacherous monk at Swinstead Abbey and is dying. The Bastard, who has been commanding England''s military forces and holding the realm together while John faltered, is shaken by the news. England is at a crisis point — a French invasion force is in the country, English nobles have defected, and now the king himself is mortally stricken. The Bastard immediately resolves to go to John''s side, combining grief for his king with urgent need to decide England''s next steps. The scene turns the play sharply toward its grim conclusion.' WHERE work_abbrev = 'Jn' AND div1 = 5 AND div2 = 6;

UPDATE scene_synopses SET synopsis = 'The Duke, having shed his friar''s disguise and returned to his own identity as ruler of Vienna, meets with Friar Peter and gives him precise instructions for the public confrontation he is about to stage. The Duke has orchestrated an elaborate plan to expose the corruption of his deputy Angelo and to vindicate Isabella and Mariana, whom Angelo has wronged. Various lords and attendants arrive to accompany the Duke as he makes his formal re-entry into Vienna. The scene is a brief logistical hinge: the disguise phase of the play is over and the reckoning is about to begin. Everything the Duke has observed and planned during his time as a friar will now be brought into the open.' WHERE work_abbrev = 'MM' AND div1 = 4 AND div2 = 5;

UPDATE scene_synopses SET synopsis = 'Friar Peter meets with Isabella and Mariana outside the city and carefully rehearses them for the public scene they are about to perform at the city gate when the Duke arrives. Isabella will step forward and publicly accuse Angelo of injustice, voicing grievances that will seem shocking and unbelievable to the watching crowd. Mariana will also play her assigned part at the right moment, revealing the truth of the bed-trick. Friar Peter assures them the timing is precise and they must follow the Duke''s plan exactly. The scene shows the careful stagecraft behind the Duke''s scheme: nothing in the coming confrontation will be accidental, and both women must be courageous and composed to carry it off.' WHERE work_abbrev = 'MM' AND div1 = 4 AND div2 = 6;

UPDATE scene_synopses SET synopsis = 'Gower, the Chorus narrator, steps forward to bridge a gap of many months. He explains that Pericles, believing both his wife Thaisa and his daughter Marina to be dead, has fallen into a profound and silent grief. He has let himself go completely: he refuses to eat, will not speak, neglects his appearance, and sails aimlessly without purpose or destination. His ship has drifted far across the sea and has now come to anchor at the port of Mytilene. The townspeople come out to look at the strange, haggard king who sits motionless on his ship. Gower''s narration sets the emotional stakes: Pericles is barely alive in spirit, and only something extraordinary can bring him back.' WHERE work_abbrev = 'Per' AND div1 = 5 AND div2 = 0;

UPDATE scene_synopses SET synopsis = 'Gower returns as Chorus to narrate the swift events following Pericles'' reunion with his daughter Marina. The governor of Mytilene, Lysimachus, who had met Marina in the brothel and been moved by her virtue, is now formally betrothed to her with Pericles'' blessing. The goddess Diana appeared to Pericles in a vision and commanded him to travel to her temple at Ephesus and give public thanks there. The entire fleet now sets sail for Ephesus to fulfill this divine command. Gower''s narration covers the transition efficiently, building anticipation for the final scene where yet another extraordinary reunion awaits Pericles in the temple.' WHERE work_abbrev = 'Per' AND div1 = 5 AND div2 = 2;

UPDATE scene_synopses SET synopsis = 'Silvia, the Duke of Milan''s daughter, slips away from the court at night with Sir Eglamour, a loyal knight she has enlisted to escort her through the dangerous forest to Mantua, where Valentine — the man she loves and her father has banished — is living in exile. They move swiftly and quietly, knowing that once her father discovers she is gone, armed pursuit will follow. Silvia is risking everything — her father''s rage, the journey''s dangers, and social disgrace — to be with the man she truly loves rather than marry Thurio, the suitor her father prefers. The scene is tense with urgency and shows Silvia''s courage and determination.' WHERE work_abbrev = 'TGV' AND div1 = 5 AND div2 = 1;

UPDATE scene_synopses SET synopsis = 'The Duke of Milan discovers that Silvia has vanished from the palace and quickly grasps that she has fled toward Valentine in Mantua. He immediately organizes a pursuit, gathering Thurio and Proteus to ride into the forest after her. Proteus joins the chase with particular eagerness, since he is obsessively in love with Silvia himself and sees this as his chance to reach her. Julia, who has followed Proteus all the way from Verona and is disguised as his page boy Sebastian, accompanies the party, silently enduring the pain of watching Proteus pursue another woman. The scene compresses the play''s complications into a fast-moving chase that will bring all parties to a crisis in the forest.' WHERE work_abbrev = 'TGV' AND div1 = 5 AND div2 = 2;

UPDATE scene_synopses SET synopsis = 'Paris arrives at Troilus''s lodgings with a company of Trojans to escort Cressida to the Greek camp in fulfillment of the prisoner exchange agreement. The arrangement has been made at the highest levels — the Trojan council agreed to trade Cressida for the captured warrior Antenor — and cannot now be undone. Troilus, who has only just spent his first night with Cressida after a long, tentative courtship, is granted just a few painful minutes alone with her to say goodbye. The lovers cling to each other and exchange vows of faithfulness, but the parting is forced and crushing. The scene captures the helplessness of two individuals swept apart by the machinery of war and politics.' WHERE work_abbrev = 'Tro' AND div1 = 4 AND div2 = 3;

UPDATE scene_synopses SET synopsis = 'A messenger brings Agamemnon and the assembled Greek leaders the news they have long sought: Achilles has killed Hector, the greatest warrior of Troy, and the city''s fall is now inevitable. The Greek commanders receive the report with relief and celebration, for Hector had been the one man who could hold Troy together against them. What is not celebrated is how it happened — Achilles did not meet Hector in fair single combat but surrounded him with his Myrmidons when Hector was unarmed and had set aside his weapons to rest. For Troilus, watching from the Trojan side, the loss is catastrophic and the manner of it a final proof of Greek dishonor. The scene marks the turning point after which Troy has no hope.' WHERE work_abbrev = 'Tro' AND div1 = 5 AND div2 = 9;

UPDATE scene_synopses SET synopsis = 'Fenton, who genuinely loves Anne Page despite her parents'' objections to him, meets secretly with the Host of the Garter Inn and arranges a crucial detail for that night''s plan. He needs a real vicar — not a disguised accomplice — to be present in the forest so that when he and Anne slip away from the chaos, they can be lawfully married on the spot. The Host, sympathetic to true love and happy to play a part in the intrigue, agrees to provide the clergyman. Fenton explains enough of the situation for the Host to understand the deception the parents have planned, and how Fenton intends to turn it to his and Anne''s advantage. The scene ensures the night will end with a genuine wedding, not merely an elopement.' WHERE work_abbrev = 'Wiv' AND div1 = 4 AND div2 = 6;

UPDATE scene_synopses SET synopsis = 'Ford, still using his disguise as the fictional gentleman "Brook," pays another visit to Falstaff at the Garter Inn. Falstaff, unaware that Brook and Ford are the same man, cheerfully confirms that he will keep his appointment that very night, going to Windsor Great Park dressed as Herne the Hunter as the merry wives have arranged. Ford, who has been using this disguise to monitor Falstaff''s every move, now has the confirmation he needs to be at the park himself and witness the humiliation firsthand. Falstaff is entirely unsuspecting, still believing he is on the verge of a successful seduction. The scene locks all the pieces into place for the final trick.' WHERE work_abbrev = 'Wiv' AND div1 = 5 AND div2 = 1;

UPDATE scene_synopses SET synopsis = 'Mistress Page meets with Doctor Caius and Mistress Quickly to go over the plan for the night''s fairy pageant in the park. Mistress Page has arranged for Caius to find and take away a boy dressed in green during the confusion, believing this disguised figure to be Anne Page and that he will thus elope with her daughter. What neither Caius nor Mistress Page''s preferred suitor Slender knows is that Anne has been secretly making her own arrangements with Fenton. The green-clad figure Caius will claim is not Anne at all. The scene shows the parents'' confident scheming, just before the audience understands that both parental plots are about to be undone.' WHERE work_abbrev = 'Wiv' AND div1 = 5 AND div2 = 3;

UPDATE scene_synopses SET synopsis = 'Sir Hugh Evans, the Welsh parson, has assembled a troop of the Windsor children and costumed them as fairies, elves, and hobgoblins for the night''s entertainment in the park. Evans rehearses them in their roles: they are to dance, sing, and pinch anyone they find sleeping or lying on the ground, especially any who prove morally unworthy. The real target, though the children may not fully understand it, is Falstaff, who will soon arrive at the oak tree disguised as Herne the Hunter, expecting to meet two willing wives. Evans and his fairy band are the instrument of the final humiliation the merry wives have designed. The scene buzzes with playful conspiracy just moments before Falstaff walks into the trap.' WHERE work_abbrev = 'Wiv' AND div1 = 5 AND div2 = 4;
